# Generated by Django 5.1.3 on 2025-01-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_discount_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='id',
            new_name='code',
        ),
    ]
